// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
// @flow

export default {
    CATEGORY_CHANNEL_OPEN_TIME: 'channel_open_time',
    CATEGORY_CHANNEL_APPROXIMATE_VIEW_TIME: 'channel_approximate_view_time',
    CATEGORY_DIRECT_CHANNEL_SHOW: 'direct_channel_show',
    CATEGORY_GROUP_CHANNEL_SHOW: 'group_channel_show',
    CATEGORY_FLAGGED_POST: 'flagged_post',
    CATEGORY_FAVORITE_CHANNEL: 'favorite_channel',
    CATEGORY_AUTO_RESET_MANUAL_STATUS: 'auto_reset_manual_status',

    CATEGORY_NOTIFICATIONS: 'notifications',

    COMMENTS: 'comments',
    COMMENTS_ANY: 'any',
    COMMENTS_ROOT: 'root',
    COMMENTS_NEVER: 'never',

    EMAIL: 'email',

    EMAIL_INTERVAL: 'email_interval',
    INTERVAL_FIFTEEN_MINUTES: 15 * 60,
    INTERVAL_HOUR: 60 * 60,
    INTERVAL_IMMEDIATE: 30, // "immediate" is a 30 second interval
    INTERVAL_NEVER: 0,
    INTERVAL_NOT_SET: -1,

    CATEGORY_DISPLAY_SETTINGS: 'display_settings',
    NAME_NAME_FORMAT: 'name_format',
    DISPLAY_PREFER_NICKNAME: 'nickname_full_name',
    DISPLAY_PREFER_FULL_NAME: 'full_name',

    MENTION_KEYS: 'mention_keys',

    USE_MILITARY_TIME: 'use_military_time',

    CATEGORY_SIDEBAR_SETTINGS: 'sidebar_settings',

    CATEGORY_ADVANCED_SETTINGS: 'advanced_settings',
    ADVANCED_FILTER_JOIN_LEAVE: 'join_leave',
    ADVANCED_CODE_BLOCK_ON_CTRL_ENTER: 'code_block_ctrl_enter',
    ADVANCED_SEND_ON_CTRL_ENTER: 'send_on_ctrl_enter',

    CATEGORY_THEME: 'theme',
    THEMES: {
        default: {
            type: 'Steedos',
            sidebarBg: '#323a4b',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#0d81c0',
            sidebarTextActiveBorder: '#13a0d4',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#222c3f',
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#06d6a0',
            awayIndicator: '#ffbc42',
            dndIndicator: '#f74343',
            mentionBj: '#fb3f38',
            mentionColor: '#ffffff',
            centerChannelBg: '#ffffff',
            centerChannelColor: '#3d3c40',
            newMessageSeparator: '#ff8800',
            linkColor: '#13a0d4',
            buttonBg: '#13a0d4',
            buttonColor: '#ffffff',
            errorTextColor: '#fd5960',
            mentionHighlightBg: '#ffe577',
            mentionHighlightLink: '#13a0d4',
            codeTheme: 'github',
            mobileBg: '#f4f3f4',
            mobileSectionItemBg: '#ffffff',
            mobileSectionItemTextColor: '#000000',
            mobileSectionHeaderTextColor: '#666666',
            mobileSectionSeperator: '#ededf0',
            mobileTabBg: '#f8f8f8',
            mobileTabTextColor: '#a6a8ab',
            mobileTabSelectedTextColor: '#222c3f',
            mobileNavBarBg: '#222c3f',
            mobileNavBarTextColor: '#ffffff',
        },
        organization: {
            type: 'Organization',
            sidebarBg: '#2071a7',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#136197',
            sidebarTextActiveBorder: '#7ab0d6',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#2f81b7',
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#7dbe00',
            awayIndicator: '#dcbd4e',
            dndIndicator: '#ff6a6a',
            mentionBj: '#fb3f38',
            mentionColor: '#ffffff',
            centerChannelBg: '#f2f4f8',
            centerChannelColor: '#333333',
            newMessageSeparator: '#ff8800',
            linkColor: '#2f81b7',
            buttonBg: '#1dacfc',
            buttonColor: '#ffffff',
            errorTextColor: '#a94442',
            mentionHighlightBg: '#f3e197',
            mentionHighlightLink: '#2f81b7',
            codeTheme: 'github',
            mobileBg: '#f8f8f8',
            mobileSectionItemBg: '#ffffff',
            mobileSectionItemTextColor: '#000000',
            mobileSectionHeaderTextColor: '#666666',
            mobileSectionSeperator: '#dddddd',
            mobileTabBg: '#ffffff',
            mobileTabTextColor: '#666666',
            mobileTabSelectedTextColor: '#2f81b7',
            mobileNavBarBg: '#2f81b7',
            mobileNavBarTextColor: '#ffffff',
        },
        mattermostDark: {
            type: 'Steedos Dark',
            sidebarBg: '#1b2c3e',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#4a5664',
            sidebarTextActiveBorder: '#66b9a7',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#1b2c3e',
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#65dcc8',
            awayIndicator: '#c1b966',
            dndIndicator: '#e81023',
            mentionBj: '#fb3f38',
            mentionColor: '#ffffff',
            centerChannelBg: '#2f3e4e',
            centerChannelColor: '#dddddd',
            newMessageSeparator: '#5de5da',
            linkColor: '#a4ffeb',
            buttonBg: '#4cbba4',
            buttonColor: '#ffffff',
            errorTextColor: '#ff6461',
            mentionHighlightBg: '#984063',
            mentionHighlightLink: '#a4ffeb',
            codeTheme: 'solarized-dark',
            mobileBg: '#f8f8f8',
            mobileSectionItemBg: '#ffffff',
            mobileSectionItemTextColor: '#000000',
            mobileSectionHeaderTextColor: '#666666',
            mobileSectionSeperator: '#dddddd',
            mobileTabBg: '#ffffff',
            mobileTabTextColor: '#666666',
            mobileTabSelectedTextColor: '#1b2c3e',
            mobileNavBarBg: '#1b2c3e',
            mobileNavBarTextColor: '#ffffff',
        },
        windows10: {
            type: 'Windows Dark',
            sidebarBg: '#171717',
            sidebarText: '#ffffff',
            sidebarUnreadText: '#ffffff',
            sidebarTextHoverBg: '#302e30',
            sidebarTextActiveBorder: '#196caf',
            sidebarTextActiveColor: '#ffffff',
            sidebarHeaderBg: '#1f1f1f',
            sidebarHeaderTextColor: '#ffffff',
            onlineIndicator: '#399fff',
            awayIndicator: '#c1b966',
            dndIndicator: '#e81023',
            mentionBj: '#fb3f38',
            mentionColor: '#ffffff',
            centerChannelBg: '#1f1f1f',
            centerChannelColor: '#dddddd',
            newMessageSeparator: '#cc992d',
            linkColor: '#0d93ff',
            buttonBg: '#0177e7',
            buttonColor: '#ffffff',
            errorTextColor: '#ff6461',
            mentionHighlightBg: '#784098',
            mentionHighlightLink: '#a4ffeb',
            codeTheme: 'monokai',
            mobileBg: '#f8f8f8',
            mobileSectionItemBg: '#ffffff',
            mobileSectionItemTextColor: '#000000',
            mobileSectionHeaderTextColor: '#666666',
            mobileSectionSeperator: '#dddddd',
            mobileTabBg: '#ffffff',
            mobileTabTextColor: '#666666',
            mobileTabSelectedTextColor: '#1f1f1f',
            mobileNavBarBg: '#1f1f1f',
            mobileNavBarTextColor: '#ffffff',
        },
    },
};
